/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gantennes;

import java.awt.Image;
import java.awt.Toolkit;
import java.awt.event.WindowEvent;
import java.awt.event.WindowListener;
import java.io.IOException;
import java.nio.charset.Charset;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.nio.file.StandardOpenOption;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author nadorfix
 */
public class Principale extends javax.swing.JFrame {

    /**
     * Creates new form Principale
     */
    public Principale() {
        super("Réseau Mobile");
        initComponents();
        try {
                Path path = Paths.get("C:\\Users\\Nabil\\Desktop\\Gantennes\\Gantennes\\antennes.txt");
                List<String> list = Files.readAllLines(path,Charset.forName("ISO-8859-1"));
                DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
                int i=0;
                int j=1;
                int k=2;
                while(k<list.size())
                {
                     model.addRow(new Object[]{list.get(i),list.get(j),list.get(k)}); 
                     k=k+3;
                     j=j+3;
                     i=i+3;
                }
                
            }catch (IOException ex) {
                Logger.getLogger(ListeAntennes.class.getName()).log(Level.SEVERE, null, ex);
            }
        
        addWindowListener(new WindowListener() {
            @Override
            public void windowOpened(WindowEvent e) {
            }

            @Override
            public void windowClosing(WindowEvent e) {
                if (JOptionPane.showConfirmDialog(PanelPrincial, "voulez-vous vraiment quitter") == JOptionPane.OK_OPTION) {
                    PanelPrincial.setVisible(false);
                   dispose();
                }
            }

            @Override
            public void windowClosed(WindowEvent e) {
            }

            @Override
            public void windowIconified(WindowEvent e) {
            }

            @Override
            public void windowDeiconified(WindowEvent e) {
            }

            @Override
            public void windowActivated(WindowEvent e) {
            }

            @Override
            public void windowDeactivated(WindowEvent e) {
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        menu = new javax.swing.JPanel();
        Ajouter = new javax.swing.JLabel();
        liste = new javax.swing.JLabel();
        antenne = new javax.swing.JLabel();
        requet = new javax.swing.JLabel();
        PanelPrincial = new javax.swing.JPanel();
        Add = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        nom = new javax.swing.JTextField();
        x = new javax.swing.JTextField();
        y = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        lis = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        antennes = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        reque = new javax.swing.JPanel();
        requetes = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        Affectati1 = new javax.swing.JTabbedPane();
        enRo1 = new javax.swing.JPanel();
        jSeparator17 = new javax.swing.JSeparator();
        jSeparator18 = new javax.swing.JSeparator();
        jSeparator19 = new javax.swing.JSeparator();
        jSeparator20 = new javax.swing.JSeparator();
        jLabel59 = new javax.swing.JLabel();
        jLabel60 = new javax.swing.JLabel();
        jLabel61 = new javax.swing.JLabel();
        jLabel62 = new javax.swing.JLabel();
        grues = new javax.swing.JPanel();
        jSeparator21 = new javax.swing.JSeparator();
        jSeparator22 = new javax.swing.JSeparator();
        jSeparator23 = new javax.swing.JSeparator();
        jSeparator24 = new javax.swing.JSeparator();
        jLabel63 = new javax.swing.JLabel();
        jLabel64 = new javax.swing.JLabel();
        jLabel65 = new javax.swing.JLabel();
        jLabel66 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        menu.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        menu.setOpaque(false);
        menu.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Ajouter.setText("Ajouter ");
        Ajouter.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AjouterMouseClicked(evt);
            }
        });
        menu.add(Ajouter, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 100, 50));

        liste.setText(" Lister ");
        liste.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                listeMouseClicked(evt);
            }
        });
        menu.add(liste, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, 100, 60));

        antenne.setIcon(new javax.swing.ImageIcon("C:\\Users\\Nabil\\Desktop\\Gantennes\\Gantennes\\src\\images\\Triangle.png")); // NOI18N
        antenne.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                antenneMouseClicked(evt);
            }
        });
        menu.add(antenne, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 100, 60));

        requet.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                requetMouseClicked(evt);
            }
        });
        menu.add(requet, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 280, 110, 60));

        getContentPane().add(menu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 120, 490));

        PanelPrincial.setOpaque(false);
        PanelPrincial.setLayout(new java.awt.CardLayout());

        Add.setOpaque(false);
        Add.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nom", "X", "Y"
            }
        ));
        jScrollPane4.setViewportView(table);

        Add.add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 360, -1, 90));

        jLabel1.setText("Nom d'antenne :");
        Add.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 130, -1, -1));

        jLabel2.setText("X :");
        Add.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 160, -1, -1));

        jLabel3.setText("Y :");
        Add.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 200, -1, -1));
        Add.add(nom, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 130, 150, -1));
        Add.add(x, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 160, 150, -1));
        Add.add(y, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 200, 150, -1));

        jButton2.setText("Ajouter");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        Add.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 260, -1, -1));

        jButton3.setText("Quitter");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        Add.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 260, -1, -1));

        PanelPrincial.add(Add, "card2");

        lis.setOpaque(false);
        lis.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("Liste des antennes");
        lis.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 30, -1, -1));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nom", "X", "Y"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        lis.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 110, -1, 220));

        jButton1.setText("Quitter");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        lis.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 410, -1, -1));

        PanelPrincial.add(lis, "card3");

        antennes.setOpaque(false);
        antennes.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setForeground(new java.awt.Color(255, 255, 255));
        jPanel3.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jPanel3MouseDragged(evt);
            }
        });

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gantennes/mulhouse.JPG"))); // NOI18N
        jLabel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLabel5.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jLabel5MouseDragged(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 1060, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 473, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        antennes.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        PanelPrincial.add(antennes, "card4");

        reque.setOpaque(false);
        reque.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        requetes.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        requetes.setForeground(new java.awt.Color(255, 0, 0));
        reque.add(requetes, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 10, 90, 30));
        reque.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 10, -1, -1));

        enRo1.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout enRo1Layout = new javax.swing.GroupLayout(enRo1);
        enRo1.setLayout(enRo1Layout);
        enRo1Layout.setHorizontalGroup(
            enRo1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(enRo1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(enRo1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(enRo1Layout.createSequentialGroup()
                        .addComponent(jSeparator20, javax.swing.GroupLayout.PREFERRED_SIZE, 469, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(48, Short.MAX_VALUE))
                    .addGroup(enRo1Layout.createSequentialGroup()
                        .addGroup(enRo1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSeparator17, javax.swing.GroupLayout.PREFERRED_SIZE, 469, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(enRo1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jSeparator18, javax.swing.GroupLayout.DEFAULT_SIZE, 469, Short.MAX_VALUE)
                                .addComponent(jSeparator19)))
                        .addGap(0, 0, Short.MAX_VALUE))))
            .addGroup(enRo1Layout.createSequentialGroup()
                .addGap(109, 109, 109)
                .addComponent(jLabel60, javax.swing.GroupLayout.PREFERRED_SIZE, 328, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(enRo1Layout.createSequentialGroup()
                .addGap(161, 161, 161)
                .addComponent(jLabel62, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, enRo1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(enRo1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, enRo1Layout.createSequentialGroup()
                        .addComponent(jLabel61, javax.swing.GroupLayout.PREFERRED_SIZE, 288, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(122, 122, 122))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, enRo1Layout.createSequentialGroup()
                        .addComponent(jLabel59, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(157, 157, 157))))
        );
        enRo1Layout.setVerticalGroup(
            enRo1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, enRo1Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(jLabel59, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator20, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel60, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator19, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel61, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jSeparator18, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel62, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator17, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41))
        );

        Affectati1.addTab("Engins Roulants", enRo1);

        grues.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout gruesLayout = new javax.swing.GroupLayout(grues);
        grues.setLayout(gruesLayout);
        gruesLayout.setHorizontalGroup(
            gruesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(gruesLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(gruesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(gruesLayout.createSequentialGroup()
                        .addComponent(jSeparator24, javax.swing.GroupLayout.PREFERRED_SIZE, 469, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(48, Short.MAX_VALUE))
                    .addGroup(gruesLayout.createSequentialGroup()
                        .addGroup(gruesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSeparator21, javax.swing.GroupLayout.PREFERRED_SIZE, 469, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(gruesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jSeparator22, javax.swing.GroupLayout.DEFAULT_SIZE, 469, Short.MAX_VALUE)
                                .addComponent(jSeparator23)))
                        .addGap(0, 0, Short.MAX_VALUE))))
            .addGroup(gruesLayout.createSequentialGroup()
                .addGap(109, 109, 109)
                .addComponent(jLabel64, javax.swing.GroupLayout.PREFERRED_SIZE, 328, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(gruesLayout.createSequentialGroup()
                .addGap(161, 161, 161)
                .addComponent(jLabel66, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, gruesLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(gruesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, gruesLayout.createSequentialGroup()
                        .addComponent(jLabel65, javax.swing.GroupLayout.PREFERRED_SIZE, 288, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(122, 122, 122))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, gruesLayout.createSequentialGroup()
                        .addComponent(jLabel63, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(157, 157, 157))))
        );
        gruesLayout.setVerticalGroup(
            gruesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, gruesLayout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(jLabel63, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator24, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel64, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator23, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel65, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jSeparator22, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel66, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator21, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41))
        );

        Affectati1.addTab("Grues", grues);

        reque.add(Affectati1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 540, 400));

        PanelPrincial.add(reque, "card5");

        getContentPane().add(PanelPrincial, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 10, 1090, 510));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AjouterMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AjouterMouseClicked
        // TODO add your handling code here:
        PanelPrincial.removeAll();
        PanelPrincial.repaint();
        PanelPrincial.revalidate();

        PanelPrincial.add(Add);
        PanelPrincial.repaint();
        PanelPrincial.revalidate();
    }//GEN-LAST:event_AjouterMouseClicked

    private void listeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_listeMouseClicked
        // TODO add your handling code here:
        PanelPrincial.removeAll();
        PanelPrincial.repaint();
        PanelPrincial.revalidate();

        PanelPrincial.add(lis);
        PanelPrincial.repaint();
        PanelPrincial.revalidate();
    }//GEN-LAST:event_listeMouseClicked

    private void antenneMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_antenneMouseClicked
        // TODO add your handling code here:
        PanelPrincial.removeAll();
        PanelPrincial.repaint();
        PanelPrincial.revalidate();
        
        
        try {
                Path path = Paths.get("C:\\Users\\Nabil\\Desktop\\Gantennes\\Gantennes\\antennes.txt");
                List<String> list = Files.readAllLines(path,Charset.forName("ISO-8859-1"));
                int i=0;
                int j=1;
                int k=2;
                
                while(k<list.size())
                {
                    
                    Point p = new Point(Integer.parseInt(list.get(j)),Integer.parseInt(list.get(k)));
                    
                    jPanel3.add(p);
                    p.setSize(jPanel3.getWidth(),jPanel3.getWidth());
                    
                     k=k+3;
                     j=j+3;
                     i=i+3;
                     
                }
                
            }catch (IOException ex) {
                Logger.getLogger(ListeAntennes.class.getName()).log(Level.SEVERE, null, ex);
            }
        PanelPrincial.add(antennes);
        PanelPrincial.repaint();
        PanelPrincial.revalidate();
        
    }//GEN-LAST:event_antenneMouseClicked

    private void requetMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_requetMouseClicked
        // TODO add your handling code here:
        PanelPrincial.removeAll();
        PanelPrincial.repaint();
        PanelPrincial.revalidate();

        PanelPrincial.add(reque);
        PanelPrincial.repaint();
        PanelPrincial.revalidate();
    }//GEN-LAST:event_requetMouseClicked

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel) table.getModel();
        model.addRow(new Object[]{nom.getText(),x.getText(),y.getText()});
        Path path = Paths.get("C:\\Users\\Nabil\\Desktop\\Gantennes\\Gantennes\\antennes.txt");
        String a = nom.getText();
        String b = x.getText();
        String c = y.getText();
        String texte = a+"\n"+b+"\n"+c+"\n";
        try{
            Files.write(path,texte.getBytes(), StandardOpenOption.CREATE,
                StandardOpenOption.WRITE,StandardOpenOption.APPEND);

        }
        catch(IOException ex){
            Logger.getLogger(Ajouter.class.getName()).log(Level.SEVERE,null,ex);

        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jLabel5MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseDragged
        // TODO add your handling code here:
      //  jLabel1.setLocation(evt.getX(), evt.getY());
    }//GEN-LAST:event_jLabel5MouseDragged

    private void jPanel3MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel3MouseDragged
        // TODO add your handling code here:
        // jPanel3.setLocation(evt.getX(), evt.getY());
    }//GEN-LAST:event_jPanel3MouseDragged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principale.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principale.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principale.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principale.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principale().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Add;
    private javax.swing.JTabbedPane Affectati1;
    private javax.swing.JLabel Ajouter;
    private javax.swing.JPanel PanelPrincial;
    private javax.swing.JLabel antenne;
    private javax.swing.JPanel antennes;
    private javax.swing.JPanel enRo1;
    private javax.swing.JPanel grues;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel59;
    private javax.swing.JLabel jLabel60;
    private javax.swing.JLabel jLabel61;
    private javax.swing.JLabel jLabel62;
    private javax.swing.JLabel jLabel63;
    private javax.swing.JLabel jLabel64;
    private javax.swing.JLabel jLabel65;
    private javax.swing.JLabel jLabel66;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JSeparator jSeparator17;
    private javax.swing.JSeparator jSeparator18;
    private javax.swing.JSeparator jSeparator19;
    private javax.swing.JSeparator jSeparator20;
    private javax.swing.JSeparator jSeparator21;
    private javax.swing.JSeparator jSeparator22;
    private javax.swing.JSeparator jSeparator23;
    private javax.swing.JSeparator jSeparator24;
    private javax.swing.JTable jTable1;
    private javax.swing.JPanel lis;
    private javax.swing.JLabel liste;
    private javax.swing.JPanel menu;
    private javax.swing.JTextField nom;
    private javax.swing.JPanel reque;
    private javax.swing.JLabel requet;
    private javax.swing.JLabel requetes;
    private javax.swing.JTable table;
    private javax.swing.JTextField x;
    private javax.swing.JTextField y;
    // End of variables declaration//GEN-END:variables
}
